config/routes.rb
Uploadify::Application.routes.draw do
  resources :uploads

   root :to => "Uploads#index"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible  :photo
  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => ['application/pdf']
end
#<div class="uploadifyQueueItem" id="upload_photoTNFLLU">								<div class="cancel">									<a href="javascript:jQuery('#upload_photo').uploadifyCancel('TNFLLU')"><img border="0" src="/uploadify/cancel.png"></a>								</div>								<span class="fileName">127.Hours.2010.DVDSC... (1281.76MB)</span><span class="percentage"> - 11%</span>								<div class="uploadifyProgress">									<div class="uploadifyProgressBar" id="upload_photoTNFLLUProgressBar" style="width: 11%;"><!--Progress Bar--></div>								</div>							</div>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end
  def create
    newparams = coerce(params)
    @upload = Upload.new(newparams[:upload])
    if @upload.save
      render :json => { :status=>true, :result => 'PDF is uploaded successfully!', :file_name => @upload.photo_file_name, :id=>@upload.id }
    else
      render :json => { :status=>false, :result => 'Only PDF file are allowed for upload.', :file_name => @upload.photo_file_name } 
    end
  end

  def show
    send_file(Upload.find(params[:id]).photo.path)
  end
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to(uploads_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def coerce(params)
    if params[:upload].nil?
      h = Hash.new
      h[:upload] = Hash.new
      h[:upload][:photo] = params[:Filedata]
      h[:upload][:photo].content_type = MIME::Types.type_for(h[:upload][:photo].original_filename).to_s
      h
    else
      params
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag :all %>
   <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js", "jquery.rails.js", "application.js" %>
     
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/_upload.html.erb
<div class="upload"> 
	<%= image_tag upload.photo.url %>
</div>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<%= javascript_include_tag "swfobject.js", "jquery.uploadify.v2.1.0.js" %>
<script type="text/javascript" charset="utf-8">
<%- session_key = Rails.application.config.session_options[:key] -%>
  $(document).ready(function() {

  $('#upload_photo').click(function(event){
  event.preventDefault();
  });

  $('#upload_photo').uploadify({
  uploader : '/uploadify/uploadify.swf',
  cancelImg : '/uploadify/cancel.png',
  multi : true,
  auto : true,
  script : '/uploads',
  onComplete : function(event, queueID, fileObj, response, data) {
  var dat = eval('(' + response + ')');
  $('#messege').html(dat.result);
  if(dat.status){
  $('#uploaded_pdfs').html('<a href="/uploads/'+dat.id+'"><img src="/images/pdfLogo.gif"> '+ dat.file_name+'</a><a rel="nofollow" data-method="delete" data-confirm="Are you sure?" href="/uploads/'+dat.id+'"> (delete)</a>'+'<br/>'+$('#uploaded_pdfs').html());
  }
  },
  scriptData : {
  '_http_accept': 'application/javascript',
  'format' : 'json',
  '_method': 'post',
  '<%= session_key %>' : encodeURIComponent('<%= u cookies[session_key] %>'),
  'authenticity_token': encodeURIComponent('<%= u form_authenticity_token %>')
  }
  });

  $('#upload_submit').click(function(event){
  event.preventDefault();
  $('#upload_photo').uploadifyUpload();
  });

  });
</script>

<div id="messege"></div>
<%= form_for Upload.new, :html => {:multipart => true} do |f| %>
  <p>
    <%= f.file_field :photo %>
  </p>
<%end%>
<div id="uploaded_pdfs">
  <%@uploads.each do |upload|%>
    <a href="/uploads/<%=upload.id%>"><%= image_tag "pdfLogo.gif" %> <%= upload.photo_file_name %></a>
    <%= link_to ' (delete)', upload, :confirm => 'Are you sure?', :method => :delete %>
    <br />
  <%end%>
</div>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.js.erb
$('#photos_count').html('<%= pluralize(@total_uploads.count, "Photo") %>');
$('#uploads').append("<%= escape_javascript(render(:partial => "uploads/upload", :locals => {:upload => @upload})) %>");